import type { SearchPayload } from '../types/searchPayload';

export const EMPTY_PAYLOAD: SearchPayload = {
  fields: [],
  skip: 0,
  limit: 20,
  sort_by: '',
  sort_order: 'ascending',
  include_count: false,
  is_auto_spell_correction: false,
  is_auto_spell_correction_zero_results: false,
  did_you_mean_limit: 0,
  session_id: '',
  user_id: '',
  facets: [],
  filters: [],
  currency: '',
  bypass_cache: false,
  bypass_merchandising: false,
  bypass_personalization: false,
  bypass_merchandising_include_filter_rule: false,
  bypass_merchandising_exclude_filter_rule: false,
  bypass_merchandising_boost_rule: false,
  bypass_merchandising_bury_rule: false,
  bypass_merchandising_sort_rule: false,
  bypass_merchandising_pin_rule: false,
  bypass_merchandising_slot_rule: false,
  bypass_merchandising_banner_rule: false,
  out_of_stock: '',
  algorithm_id: '',
  algorithm_variant_id: '',
  auto_redirect: false,
  location: '',
  price_group: '',
  currency_conversion_rate: 0,
  selected_variant_fields: [],
  skip_facet_generation: false,
  merchandising_rule_override: [],
  variation_map_group_by: [],
  variation_map_group_values: [],
};

export const LOCAL_STORAGE_KEY = 'search_debugger_payload';
export const PAYLOAD_VERSION = 5;
