import type { SearchResponse } from '../types/searchResponse';

export const MOCK_RESPONSE: SearchResponse = {
  records: [
    {
      id: '8daae96c-676d-5da2-a6a4-9c7bff0b6c94',
      name: 'Adidas Product 6636',
      provider_id: 'prod_6636',
      brand: 'Adidas',
      selected_variant: { id: 'bd77f819', name: 'Adidas Variant 10031 - L Red', provider_id: 'var_10031', color: 'Red' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 1, is_pin: false, is_slotted: false },
    },
    {
      id: 'af708e96-4ba9-5cd0-b051-15052926ea2b',
      name: 'Adidas Product 404',
      provider_id: 'prod_404',
      brand: 'Adidas',
      selected_variant: { id: 'c5ba522f', name: 'Adidas Variant 10043 - L Black', provider_id: 'var_10043', color: 'Black' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 2, is_pin: false, is_slotted: false },
    },
    {
      id: 'd5564d3a-64aa-5e1f-9dff-c45f72117e2d',
      name: 'Adidas Product 1684',
      provider_id: 'prod_1684',
      brand: 'Adidas',
      selected_variant: { id: '729dfb50', name: 'Adidas Variant 10120 - XL Green', provider_id: 'var_10120', color: 'Green' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 3, is_pin: false, is_slotted: false },
    },
    {
      id: '7b138f44-6645-57f3-9100-cafcf916d7b7',
      name: 'Adidas Product 4084',
      provider_id: 'prod_4084',
      brand: 'Adidas',
      selected_variant: { id: '61603b12', name: 'Adidas Variant 10137 - S Blue', provider_id: 'var_10137', color: 'Blue' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 4, is_pin: false, is_slotted: false },
    },
    {
      id: 'dde90d5d-1afe-50df-9697-1af5ce24deab',
      name: 'Adidas Product 5820',
      provider_id: 'prod_5820',
      brand: 'Adidas',
      selected_variant: { id: '127a604c', name: 'Adidas Variant 10268 - XL Black', provider_id: 'var_10268', color: 'Black' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 5, is_pin: false, is_slotted: false },
    },
    {
      id: 'af1be717-76c1-5d8a-a38b-86c58ef5a030',
      name: 'Adidas Product 8524',
      provider_id: 'prod_8524',
      brand: 'Adidas',
      selected_variant: { id: '72fb0c92', name: 'Adidas Variant 10300 - XL Green', provider_id: 'var_10300', color: 'Green' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 6, is_pin: false, is_slotted: false },
    },
    {
      id: 'cbe1a373-f0e8-52bb-9b1f-a405f5150b53',
      name: 'Adidas Product 9652',
      provider_id: 'prod_9652',
      brand: 'Adidas',
      selected_variant: { id: '65d2dee6', name: 'Adidas Variant 1046 - M Red', provider_id: 'var_1046', color: 'Red' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 7, is_pin: false, is_slotted: false },
    },
    {
      id: '7d59c4aa-36cc-5157-8f4c-e79d783b8e14',
      name: 'Adidas Product 1436',
      provider_id: 'prod_1436',
      brand: 'Adidas',
      selected_variant: { id: '23f6470c', name: 'Adidas Variant 10508 - XL Black', provider_id: 'var_10508', color: 'Black' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 8, is_pin: false, is_slotted: false },
    },
    {
      id: 'a572813d-3bfa-50d3-b468-b7e985cf9346',
      name: 'Adidas Product 5788',
      provider_id: 'prod_5788',
      brand: 'Adidas',
      selected_variant: { id: '335eecd9', name: 'Adidas Variant 10523 - L Black', provider_id: 'var_10523', color: 'Black' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 9, is_pin: false, is_slotted: false },
    },
    {
      id: '87102aaa-7b5e-5338-b63d-909a9f19efd0',
      name: 'Adidas Product 1132',
      provider_id: 'prod_1132',
      brand: 'Adidas',
      selected_variant: { id: '3d9695e1', name: 'Adidas Variant 10555 - L Green', provider_id: 'var_10555', color: 'Green' },
      ranking_info: { overall_score: 0.16815469, merchandising_score: 1, relevance_score: 0.16815469, personalization_score: null, performance_score: null, position: 10, is_pin: false, is_slotted: false },
    },
  ],
  facets: [
    {
      name: 'Brand',
      field: 'brand',
      appearance: 'Terms',
      default_collapse_on_desktop: false,
      default_collapse_on_mobile: false,
      show_count: true,
      show_search_within_facet: false,
      display_tooltip: false,
      tooltip: '',
      hide_empty_value: false,
      layout_style: '',
      display_layout: '',
      star_color: '',
      values: [
        { display_value: 'Adidas', count: 529, image_url: null, color: null, value: 'Adidas', min: null, max: null },
        { display_value: 'Sony',   count: 524, image_url: null, color: null, value: 'Sony',   min: null, max: null },
        { display_value: 'LG',     count: 517, image_url: null, color: null, value: 'LG',     min: null, max: null },
        { display_value: 'Nike',   count: 514, image_url: null, color: null, value: 'Nike',   min: null, max: null },
        { display_value: 'HP1',    count: 508, image_url: null, color: null, value: 'HP',     min: null, max: null },
        { display_value: 'Apple',  count: 505, image_url: null, color: null, value: 'Apple',  min: null, max: null },
        { display_value: 'Samsung',count: 490, image_url: null, color: null, value: 'Samsung',min: null, max: null },
        { display_value: 'Dell',   count: 472, image_url: null, color: null, value: 'Dell',   min: null, max: null },
      ],
      range: null,
    },
    {
      name: 'Price',
      field: 'price',
      appearance: 'Range',
      default_collapse_on_desktop: false,
      default_collapse_on_mobile: false,
      show_count: true,
      show_search_within_facet: false,
      display_tooltip: false,
      tooltip: '',
      hide_empty_value: false,
      layout_style: '',
      display_layout: '',
      star_color: '',
      values: null,
      range: { min: 12.92, max: 995.82, step: 1 },
    },
  ],
  banners: [],
  meta: {
    did_you_mean: null,
    auto_spell_correction_applied: true,
    redirect_url: null,
    tagged_attributes: null,
    total_count: 1001,
    corrected_search_term: null,
    experiments: null,
  },
};

export const RESULTS_STORAGE_KEY = 'search_debugger_results';
